version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: text-search
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    restart: always
    environment:
      DB_URI: 'postgresql+psycopg2://app:app@db:5432/text-search'
    volumes:
      - './backend:/app'
    ports:
      - "5000:5000"
    depends_on:
      - db

  front:
    container_name: front
    build:
      context: .
      dockerfile: deploy/Dockerfile.front
    volumes:
      - './front:/app'
      - './front/node_modules:/app/node_modules'
    ports:
      - '80:80'
    depends_on:
      - backend